apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xeu5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xeu5
    app.kubernetes.io/part-of: ci1t-43256-0040-app
  name: devfile-sample-xeu5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xeu5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xeu5
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0040-tenant/ci1t-43256-0040-app/devfile-sample-xeu5@sha256:834678f23f91660db688eca7cf7edccf5dbf1f6effdfd43abc7659af58776e46
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
